version: 0.2

phases:
  build:
    commands:
      - ls
      - if test -d AWSCoreWCFServerExtensions; then cd AWSCoreWCFServerExtensions; fi
      - dotnet restore
      - dotnet tool restore
      - dotnet build -c Release
artifacts:
  files:
    - '**/*'