version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 7.0
  build:
    commands:
      - ls
      - if test -d AWSCoreWCFServerExtensions; then cd AWSCoreWCFServerExtensions; fi
      - dotnet restore
      - dotnet tool restore
      - dotnet build -c Release
artifacts:
  files:
    - '**/*'