name: Build and Deploy

on:
  push:
    branches:
    - main
  pull_request:
env:
  AWS_REGION : "us-west-2"
# permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Versions
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
    - name: Install dependencies
      run: |
        dotnet restore
        dotnet tool restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_INTEGRATION_TEST_ROLE }}
        role-session-name: github-cicd
        aws-region: ${{ env.AWS_REGION }}
    - name: Test
      # runs all automated tests
      run: dotnet test --configuration Release --no-restore --verbosity normal

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v2
      # set fetch-depth to 0 to get full git history, needed for NerdBank GitVersion to caclulate version
      with:
        fetch-depth: 0
    - name: Zip Src
      run: |
        #cd ../
        zip -r AWSCoreWCFServerExtensions.zip .
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
        role-session-name: github-cicd
        aws-region: ${{ env.AWS_REGION }}
    - name: Start Deployment Pipeline
      # uploading this zip archive will trigger a CodePipeline that will build, sign, and package
      # the dlls and then publish them to nuget.org
      run: aws s3 cp ./AWSCoreWCFServerExtensions.zip s3://${{ secrets.AWS_DEPLOYMENT_BUCKET_NAME }}/AWSCoreWCFServerExtensions.zip

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Versions
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
    - name: Install dependencies
      run: |
        dotnet restore
        dotnet tool restore
    - name: Lint
      run: dotnet csharpier . --check
