name: Run CodeBuild project

on:
  push:
    branches: 
    - main
    - release/*
  pull_request:
    branches: [ main ]

jobs:
  code-build:
    runs-on: windows-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: ${{ secrets.CODEBUILD_PROJECT_NAME}}