name: Secret Detection

on:
  push:    
  pull_request:

jobs:
  scan-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: 9a92a70
          head: HEAD
          extra_args: --debug --only-verified

